#
# ASCRIPT Configuration
#
import datetime as dt

CURRENT_YEAR = dt.datetime.now().year
START_YEAR = CURRENT_YEAR+1
STOP_YEAR = CURRENT_YEAR+11
DEFAULT_YEAR = CURRENT_YEAR+6

DEFAULT_AGGREGATION_LEVEL = "County"

STATES = ["CA"]
DEFAULT_STATE = "CA"
DEFAULT_LOCATION = "Santa Clara County"

MAX_EVS = 3000000
DEFAULT_EVS = 500000
UI_EVS_STEP = 1000

MAX_CHARGERS = 3000000
DEFAULT_CHARGERS = 30500
UI_CHARGERS_STEP = 100

DEFAULT_PUBLIC = 30.0
DEFAULT_WORKPLACE = 30.0
